import type { Vehicle } from '../../types'

function getMockSummary(grade: number): string {
  if (grade >= 4.0) {
    return `This vehicle presents in strong condition with a grade of ${grade.toFixed(1)}/5, indicating minimal wear and no significant mechanical or cosmetic concerns. It represents a solid buy at auction with low risk for unexpected post-purchase costs.`
  }
  if (grade >= 2.5) {
    return `This vehicle has a condition grade of ${grade.toFixed(1)}/5, reflecting moderate wear or noted damage that warrants careful review before bidding. Buyers should factor potential repair costs into their maximum bid and inspect all disclosed damage notes.`
  }
  return `This vehicle carries a low condition grade of ${grade.toFixed(1)}/5, indicating significant damage or mechanical issues that may require substantial repair. Proceed with caution — this lot is best suited for buyers with reconditioning experience or parts-use intent.`
}

interface Props {
  vehicle: Vehicle
}

export default function BuyerIntelligenceCard({ vehicle }: Props) {
  const summary = vehicle.condition_summary ?? getMockSummary(vehicle.condition_grade)

  return (
    <section className="bg-zinc-50 border border-zinc-200 rounded-lg p-4">
      <h2 className="text-xs text-zinc-400 uppercase tracking-wide font-medium mb-3">Condition Summary</h2>
      <p className="text-sm text-zinc-700 leading-relaxed">{summary}</p>
      <p className="text-xs text-zinc-400 mt-3">Generated by Claude Haiku</p>
    </section>
  )
}
